### ISSUE TITLE
Crash to desktop on launch in 1.20.-rc.1

### ISSUE THREAD

**Issue by Ketsuna009** [TheFifthRider/LogSplitter#2]
🤷 No additional information, sorry. Maybe has something to do with the new Archive folder in Logs? 

Game Version: v1.20.0-rc.1 (Unstable)
12/4/2024 4:04:26 PM: Critical error occurred in the following mod: logsplitter@1.0.1
Loaded Mods: barkbeetle@1.0.0, moreicons@1.1.0, restoredhaircolors@1.0.0, game@1.20.0-rc.1, vsimgui@1.1.7, zoombuttonreborn@2.0.0, betterentityinteraction@1.0.2, chatping@1.0.0, commonlib@2.5.0-rc.2, configlib@1.3.17, danatweaks@3.3.5, daytrader@1.0.2, extrainfo@1.8.1, hudclockpatch@1.0.0, improvedhandbookrecipes@1.0.3, logsplitter@1.0.1, stepupadvanced@1.0.0, targetDotSmall@1.1.0, creative@1.20.0-rc.1, survival@1.20.0-rc.1, extraoverlays@1.4.0, statushudcontpatch@1.0.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at LogSplitter.LogSplitterModSystem.EntryAddedHandler(EnumLogType logType, String message, Object[] args) in C:\Users\flare\Workspace\vscode\LogSplitter\LogSplitter\src\LogSplitterModSystem.cs:line 21
   at Vintagestory.API.Common.LoggerBase.Chat(String format, Object[] args) in VintagestoryApi\Common\API\ILogger.cs:line 195
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleChatLine(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 166
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\ProcessPacketTask.cs:line 16
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\ProcessPacketTask.cs:line 10
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 785
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 740
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 329
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by TheFifthRider** [comment]
This could be the null comparison bug I fixed in 1.0.2-- can you give that version a try and let me know if you're still experiencing this?

**Comment by Ketsuna009** [comment]
ok, tried 1.0.2 and it still crashed

Running on 64 bit Windows 10.0.19045.0 with 32702 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
12/4/2024 4:25:08 PM: Critical error occurred in the following mod: logsplitter@1.0.2
Loaded Mods: barkbeetle@1.0.0, moreicons@1.1.0, restoredhaircolors@1.0.0, game@1.20.0-rc.1, vsimgui@1.1.7, zoombuttonreborn@2.0.0, chatping@1.0.0, commonlib@2.5.0-rc.2, configlib@1.3.17, danatweaks@3.3.5, daytrader@1.0.2, extrainfo@1.8.1, hudclockpatch@1.0.0, improvedhandbookrecipes@1.0.3, logsplitter@1.0.2, stepupadvanced@1.0.0, targetDotSmall@1.1.0, creative@1.20.0-rc.1, survival@1.20.0-rc.1, extraoverlays@1.4.0, statushudcontpatch@1.0.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at LogSplitter.LogSplitterModSystem.EntryAddedHandler(EnumLogType logType, String message, Object[] args) in C:\Users\flare\Workspace\vscode\LogSplitter\LogSplitter\src\LogSplitterModSystem.cs:line 19
   at Vintagestory.API.Common.LoggerBase.Chat(String format, Object[] args) in VintagestoryApi\Common\API\ILogger.cs:line 195
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleChatLine(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 166
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\ProcessPacketTask.cs:line 16
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\ProcessPacketTask.cs:line 10
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 785
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 740
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 329
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 12/4/2024 4:04:37 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x4078
Faulting application start time: 0x01db468ffebbb408
Faulting application path: C:\VS1.20-pre\Vintagestory1.20\Vintagestory.exe
Faulting module path: C:\VS1.20-pre\Vintagestory1.20\Lib\openal32.dll
Report Id: fbd70bb8-a104-40aa-948a-5f9260be0102
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/4/2024 4:02:20 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x4038
Faulting application start time: 0x01db468d690903f2
Faulting application path: C:\VS1.20-pre\Vintagestory1.20\Vintagestory.exe
Faulting module path: C:\VS1.20-pre\Vintagestory1.20\Lib\openal32.dll
Report Id: 8e563324-2016-43bf-9c20-da4ab944de96
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by TheFifthRider** [comment]
Dang. Well, thanks for the logs! I'll dig into this and see if I can reproduce it.

**Comment by TheFifthRider** [comment]
Digging around with this it seems the problem is with some log messages containing a null reference. LogSplitter should be able to handle this gracefully-- updated and released a fix in 1.0.3.
